Commit f9023a0c242cd5f8ebcf999c57def5b7240e2299 broke the build:
applet.c:939:2: error: passing argument 3 of
‘notify_notification_set_hint’ from incompatible pointer type [-Werror]

original bzr status:
revno: 2716
committer: Michael Biebl <biebl@debian.org>
timestamp: Wed 2013-01-30 02:17:22 +0100
message: