GValueArray is deprecated.  Unfortunately, it's part of our API right now, so we have to keep it around for a while.  But since it's deprecated, and we want to know about *other* deprecations, we have to suppress deprecations about GValueArray.  Unfortunately using macros to do that (eg in nm-gvaluearray-compat.h) exposes some compiler bugs due to the combination of parentheses/braces and #pragma from G_GNUC_BEGIN_IGNORE_DEPRECATIONS, resulting in warnings like:
gconf-helpers.c:1520:9: error: expected expression before '#pragma'

This is based on NM commit 80886c2866e6d61cc2f1e1b1bc26aa4ff84d0e4f, see it
for more info.

original bzr status:
revno: 2801
committer: Jiří Klimeš <jklimes@redhat.com>
timestamp: Tue 2013-03-26 15:41:50 +0100
message: